"""Build the v8 training notebook programmatically.

Uses JSON-level cell construction to avoid triple-quote nesting issues.
"""
import json
import sys
from pathlib import Path

sys.stdout.reconfigure(encoding="utf-8")

SEP = "\u2550" * 63  # ═══...
DASH = "\u2014"  # —


def md_cell(lines):
    return {
        "cell_type": "markdown",
        "metadata": {},
        "source": [l + "\n" for l in lines],
    }


def code_cell(lines):
    return {
        "cell_type": "code",
        "metadata": {},
        "source": [l + "\n" for l in lines],
        "outputs": [],
        "execution_count": None,
    }


cells = []

# =====================================================================
# CELL 0: Header
# =====================================================================
cells.append(md_cell([
    f"# Clipt v8 {DASH} Production Gap Closure Training Pipeline",
    "",
    f"**PURPOSE:** Train the models that are currently MISSING or UNDERTRAINED, closing the remaining gaps in the 60+ model detection pipeline.",
    "",
    "## Priority Models to Train",
    "",
    "| # | Model | Type | Gap | Output |",
    "|---|-------|------|-----|--------|",
    "| 1 | Football Jersey OCR v8 | YOLO detect | 0 detections on ALL football | `football_jersey_ocr_v8.pt` |",
    "| 2 | Football Player Crop v8 | YOLO detect | Cannot isolate individual players | `football_player_crop_v8.pt` |",
    "| 3 | Navy/Dark Jersey Specialist v8 | YOLO detect | Dark jerseys invisible to OCR | `navy_jersey_specialist_v8.pt` |",
    f"| 4 | Jersey Upscaler v8 | ESRGAN/SwinIR | 360p crops too small for OCR | `jersey_upscaler_v8.pth` |",
    f"| 5 | Scoreboard OCR v8 | YOLO detect | Score tracking for outcome validation | `scoreboard_ocr_v8.pt` |",
    "",
    "## What Already Works (57 models in production)",
    f"- v5 universal OCR {DASH} jersey_ocr_universal_v5.pt (best general reader)",
    f"- v5 player detector {DASH} player_detector_v5.pt",
    f"- v5 outcome classifiers {DASH} basketball/football/lacrosse",
    f"- v4 sport-specific outcome detectors {DASH} 20 models (hoop, made_shot, touchdown, etc.)",
    f"- v3 OCR specialists {DASH} 12 models (dark jersey, motion blur, wide angle, etc.)",
    f"- v2 universal {DASH} jersey_number_universal (0.995 mAP50)",
    f"- v1 fallback {DASH} digit detector, player detector, tracker",
    "",
    "## What's Missing (THIS notebook trains these)",
    f"1. **Football OCR** {DASH} v7 models were never trained. Football videos get 0 jersey detections.",
    f"2. **Dark jersey specialist** {DASH} v3 exists but undertrained. Navy/black jerseys still fail.",
    f"3. **Player crop** {DASH} Current v5 detector returns formation-sized boxes, not individuals.",
    f"4. **Super-resolution** {DASH} 360p crops are 30-50px. Need 3-4x upscale before OCR.",
    f"5. **Scoreboard** {DASH} v5 scoreboard exists but doesn't do OCR. Need digit extraction.",
    "",
    f"**Estimated time:** ~12{DASH}18 hours on A100, ~24{DASH}36 hours on T4",
    f"**GPU required:** A100 recommended (T4 works but slower)",
    "",
    "---",
]))

# =====================================================================
# CELL 1: Setup
# =====================================================================
cells.append(md_cell([
    f"## {SEP}",
    "## Section 0: Environment Setup",
    f"## {SEP}",
]))

cells.append(code_cell([
    "# ═══ Cell 0.1: Install dependencies ═══",
    "!pip install ultralytics>=8.3.0 roboflow supervision torch torchvision",
    "!pip install opencv-python-headless pillow albumentations",
    "!pip install basicsr realesrgan  # For super-resolution training",
    "",
    "import os, json, shutil, time, gc, traceback",
    "from pathlib import Path",
    "from datetime import datetime",
    "",
    "import torch",
    "import cv2",
    "import numpy as np",
    "from ultralytics import YOLO",
    "",
    "# Google Drive for persistent storage",
    "from google.colab import drive",
    "drive.mount('/content/drive')",
    "",
    "DRIVE_BASE = Path('/content/drive/MyDrive/clipt_v8_training')",
    "DRIVE_BASE.mkdir(parents=True, exist_ok=True)",
    "DATASETS = Path('/content/datasets')",
    "DATASETS.mkdir(exist_ok=True)",
    "MODELS_OUT = DRIVE_BASE / 'models'",
    "MODELS_OUT.mkdir(exist_ok=True)",
    "",
    "print(f'GPU: {torch.cuda.get_device_name(0) if torch.cuda.is_available() else \"CPU\"}')",
    "print(f'VRAM: {torch.cuda.get_device_properties(0).total_mem / 1e9:.1f} GB' if torch.cuda.is_available() else '')",
    "print(f'Drive: {DRIVE_BASE}')",
    "print(f'Models output: {MODELS_OUT}')",
]))

cells.append(code_cell([
    "# ═══ Cell 0.2: Crash protection wrapper ═══",
    "def safe_train(name, train_fn):",
    "    \"\"\"Run training with crash protection. Saves progress to Drive.\"\"\"",
    "    print(f'\\n{\"═\" * 60}')",
    "    print(f'TRAINING: {name}')",
    "    print(f'{\"═\" * 60}')",
    "    t0 = time.time()",
    "    try:",
    "        result = train_fn()",
    "        elapsed = time.time() - t0",
    "        print(f'\\n✅ {name} completed in {elapsed/3600:.1f}h')",
    "        return result",
    "    except Exception as e:",
    "        elapsed = time.time() - t0",
    "        print(f'\\n❌ {name} FAILED after {elapsed/3600:.1f}h: {e}')",
    "        traceback.print_exc()",
    "        # Save error log",
    "        log_file = MODELS_OUT / f'{name}_error.log'",
    "        with open(log_file, 'w') as f:",
    "            f.write(f'{datetime.now()}\\n{name}\\n{traceback.format_exc()}')",
    "        return None",
    "    finally:",
    "        gc.collect()",
    "        if torch.cuda.is_available(): torch.cuda.empty_cache()",
]))

# =====================================================================
# CELL 2: Dataset download
# =====================================================================
cells.append(md_cell([
    f"## {SEP}",
    "## Section 1: Download All Datasets",
    f"## {SEP}",
    "",
    "Downloads from Roboflow Universe (free, no API key needed for public datasets).",
]))

cells.append(code_cell([
    "# ═══ Cell 1.1: Download football jersey/digit datasets ═══",
    "from roboflow import Roboflow",
    "",
    "# These are all public datasets on Roboflow Universe",
    "# No API key needed for download-only",
    "",
    "DATASET_CONFIGS = [",
    "    # Football digit detection (13,815 images)",
    "    {",
    "        'workspace': 'footballplayertracking',",
    "        'project': 'jerseynumberdetectordigitdetector',",
    "        'version': 2,",
    "        'name': 'football_digits',",
    "        'format': 'yolov8',",
    "    },",
    "    # Dark jersey numbers (826 images, critical for navy)",
    "    {",
    "        'workspace': 'dark-blue-jt0mg',",
    "        'project': 'jerseynumbers',",
    "        'version': 1,",
    "        'name': 'dark_jersey_numbers',",
    "        'format': 'yolov8',",
    "    },",
    "    # Jersey number detection - volleyball/sports (6,932 images, diverse jerseys)",
    "    {",
    "        'workspace': 'volleyai-actions',",
    "        'project': 'jersey-number-detection-s01j4',",
    "        'version': 1,",
    "        'name': 'jersey_numbers_diverse',",
    "        'format': 'yolov8',",
    "    },",
    "    # Football player detection (1,232 images)",
    "    {",
    "        'workspace': 'augmented-startups',",
    "        'project': 'football-player-detection-kucab',",
    "        'version': 1,",
    "        'name': 'football_players',",
    "        'format': 'yolov8',",
    "    },",
    "    # Football pre-snap tracker",
    "    {",
    "        'workspace': 'football-tracking',",
    "        'project': 'football-presnap-tracker',",
    "        'version': 1,",
    "        'name': 'football_presnap',",
    "        'format': 'yolov8',",
    "    },",
    "]",
    "",
    "for cfg in DATASET_CONFIGS:",
    "    dest = DATASETS / cfg['name']",
    "    if dest.exists() and any(dest.rglob('*.txt')):",
    "        print(f'  ⏭ {cfg[\"name\"]} already downloaded')",
    "        continue",
    "    print(f'  ⬇ Downloading {cfg[\"name\"]}...')",
    "    try:",
    "        rf = Roboflow()",
    "        project = rf.workspace(cfg['workspace']).project(cfg['project'])",
    "        ds = project.version(cfg['version']).download(",
    "            cfg['format'],",
    "            location=str(dest),",
    "        )",
    "        print(f'  ✅ {cfg[\"name\"]}: {sum(1 for _ in dest.rglob(\"*.jpg\"))} images')",
    "    except Exception as e:",
    "        print(f'  ❌ {cfg[\"name\"]}: {e}')",
    "",
    "print('\\nDataset download complete.')",
]))

# =====================================================================
# MODEL 1: Football Jersey OCR v8
# =====================================================================
cells.append(md_cell([
    f"## {SEP}",
    "## Section 2: Football Jersey OCR v8",
    f"## {SEP}",
    "",
    "**Problem:** Football videos return 0 jersey detections. v7 was planned but never trained.",
    "",
    "**Approach:**",
    f"- Start from YOLOv8m pretrained (best accuracy/speed for OCR)",
    f"- Train on football_digits (13,815 images) + dark_jersey_numbers (826 images)",
    f"- Digit-wise detection (0{DASH}9 classes) {DASH} generalizes to unseen number combinations",
    f"- High resolution training (imgsz=1280) for small digit detection",
    f"- Heavy augmentation: mosaic, mixup, copy-paste for small objects",
    "",
    f"**Target:** mAP50 >= 0.70 on football digits",
]))

cells.append(code_cell([
    "# ═══ Cell 2.1: Merge football digit datasets ═══",
    "FOOTBALL_OCR_DATASET = DATASETS / 'football_ocr_v8_merged'",
    "",
    "def merge_datasets(sources, dest, name='merged'):",
    "    \"\"\"Merge multiple YOLO-format datasets into one.\"\"\"",
    "    dest.mkdir(parents=True, exist_ok=True)",
    "    for split in ['train', 'valid', 'test']:",
    "        (dest / split / 'images').mkdir(parents=True, exist_ok=True)",
    "        (dest / split / 'labels').mkdir(parents=True, exist_ok=True)",
    "",
    "    total = 0",
    "    for src_path in sources:",
    "        src = Path(src_path)",
    "        if not src.exists():",
    "            print(f'  ⚠ {src} not found, skipping')",
    "            continue",
    "        for split in ['train', 'valid', 'test']:",
    "            img_dir = src / split / 'images'",
    "            lbl_dir = src / split / 'labels'",
    "            if not img_dir.exists():",
    "                continue",
    "            for img in img_dir.glob('*'):",
    "                if img.suffix.lower() not in ('.jpg', '.jpeg', '.png'):",
    "                    continue",
    "                # Prefix filename to avoid collisions",
    "                prefix = src.name",
    "                new_name = f'{prefix}_{img.name}'",
    "                shutil.copy2(img, dest / split / 'images' / new_name)",
    "                # Copy matching label",
    "                lbl = lbl_dir / f'{img.stem}.txt'",
    "                if lbl.exists():",
    "                    shutil.copy2(lbl, dest / split / 'labels' / f'{prefix}_{img.stem}.txt')",
    "                total += 1",
    "",
    "    # Create data.yaml",
    "    # Read class names from first source",
    "    nc = 10  # digits 0-9",
    "    names = [str(i) for i in range(10)]",
    "    for src_path in sources:",
    "        yaml_path = Path(src_path) / 'data.yaml'",
    "        if yaml_path.exists():",
    "            import yaml",
    "            with open(yaml_path) as f:",
    "                data = yaml.safe_load(f)",
    "            if 'names' in data:",
    "                names = data['names'] if isinstance(data['names'], list) else list(data['names'].values())",
    "                nc = len(names)",
    "            break",
    "",
    "    yaml_content = f\"\"\"train: {dest / 'train' / 'images'}",
    "val: {dest / 'valid' / 'images'}",
    "test: {dest / 'test' / 'images'}",
    "nc: {nc}",
    "names: {names}",
    "\"\"\"",
    "    (dest / 'data.yaml').write_text(yaml_content)",
    "    print(f'  Merged {total} images into {dest}')",
    "    print(f'  Classes: {nc} -> {names}')",
    "    return dest / 'data.yaml'",
    "",
    "football_ocr_yaml = merge_datasets(",
    "    [DATASETS / 'football_digits', DATASETS / 'dark_jersey_numbers'],",
    "    FOOTBALL_OCR_DATASET,",
    ")",
]))

cells.append(code_cell([
    "# ═══ Cell 2.2: Train Football Jersey OCR v8 ═══",
    "def train_football_ocr_v8():",
    "    model = YOLO('yolov8m.pt')  # Medium for accuracy",
    "    results = model.train(",
    "        data=str(FOOTBALL_OCR_DATASET / 'data.yaml'),",
    "        epochs=150,",
    "        imgsz=1280,       # High res for small digits",
    "        batch=4,           # A100: batch=8, T4: batch=2-4",
    "        patience=25,",
    "        optimizer='AdamW',",
    "        lr0=0.001,",
    "        lrf=0.01,",
    "        # Heavy augmentation for small objects",
    "        mosaic=1.0,",
    "        mixup=0.3,",
    "        copy_paste=0.3,",
    "        scale=0.5,",
    "        hsv_h=0.015,",
    "        hsv_s=0.7,       # Wide saturation range for jersey colors",
    "        hsv_v=0.4,       # Brightness variation for outdoor/indoor",
    "        flipud=0.0,       # No vertical flip (digits not symmetric)",
    "        fliplr=0.5,",
    "        degrees=10.0,",
    "        translate=0.2,",
    "        shear=5.0,",
    "        name='football_jersey_ocr_v8',",
    "        project=str(DRIVE_BASE / 'runs'),",
    "        save=True,",
    "        save_period=25,    # Checkpoint every 25 epochs",
    "        plots=True,",
    "        val=True,",
    "    )",
    "    # Copy best model",
    "    best = Path(results.save_dir) / 'weights' / 'best.pt'",
    "    if best.exists():",
    "        dest = MODELS_OUT / 'football_jersey_ocr_v8.pt'",
    "        shutil.copy2(best, dest)",
    "        print(f'  Saved: {dest}')",
    "        # Validate",
    "        model = YOLO(str(dest))",
    "        val = model.val(data=str(FOOTBALL_OCR_DATASET / 'data.yaml'))",
    "        print(f'  mAP50: {val.box.map50:.4f}')",
    "        print(f'  mAP50-95: {val.box.map:.4f}')",
    "    return results",
    "",
    "safe_train('football_jersey_ocr_v8', train_football_ocr_v8)",
]))

# =====================================================================
# MODEL 2: Football Player Crop v8
# =====================================================================
cells.append(md_cell([
    f"## {SEP}",
    "## Section 3: Football Player Crop v8",
    f"## {SEP}",
    "",
    "**Problem:** player_detector_v5 returns formation-sized bounding boxes instead of individual players.",
    "",
    "**Approach:**",
    f"- Train on football player detection datasets (tight bounding boxes around individuals)",
    f"- Focus on individual player isolation, not team/formation detection",
    f"- Training at 1280px to handle wide-angle broadcast footage",
]))

cells.append(code_cell([
    "# ═══ Cell 3.1: Train Football Player Crop v8 ═══",
    "def train_football_player_crop_v8():",
    "    # Merge football player datasets",
    "    PLAYER_DATASET = DATASETS / 'football_player_crop_v8'",
    "    merge_datasets(",
    "        [DATASETS / 'football_players', DATASETS / 'football_presnap'],",
    "        PLAYER_DATASET,",
    "    )",
    "",
    "    model = YOLO('yolov8m.pt')",
    "    results = model.train(",
    "        data=str(PLAYER_DATASET / 'data.yaml'),",
    "        epochs=120,",
    "        imgsz=1280,",
    "        batch=4,",
    "        patience=20,",
    "        optimizer='AdamW',",
    "        lr0=0.001,",
    "        mosaic=1.0,",
    "        mixup=0.2,",
    "        scale=0.5,",
    "        fliplr=0.5,",
    "        degrees=5.0,",
    "        name='football_player_crop_v8',",
    "        project=str(DRIVE_BASE / 'runs'),",
    "        save=True,",
    "        save_period=20,",
    "        plots=True,",
    "    )",
    "    best = Path(results.save_dir) / 'weights' / 'best.pt'",
    "    if best.exists():",
    "        dest = MODELS_OUT / 'football_player_crop_v8.pt'",
    "        shutil.copy2(best, dest)",
    "        print(f'  Saved: {dest}')",
    "    return results",
    "",
    "safe_train('football_player_crop_v8', train_football_player_crop_v8)",
]))

# =====================================================================
# MODEL 3: Navy/Dark Jersey Specialist v8
# =====================================================================
cells.append(md_cell([
    f"## {SEP}",
    "## Section 4: Navy/Dark Jersey Specialist v8",
    f"## {SEP}",
    "",
    "**Problem:** Dark jersey numbers (navy, black, dark blue) have near-zero contrast. OCR fails consistently.",
    "",
    "**Approach:**",
    f"- Train on dark_jersey_numbers dataset (826 images {DASH} curated for dark jerseys)",
    f"- Preprocessing: CLAHE, gamma correction, channel splitting to enhance contrast",
    f"- Data augmentation: extreme brightness/contrast variation",
    f"- Fine-tune from v5 OCR universal to preserve general OCR ability",
]))

cells.append(code_cell([
    "# ═══ Cell 4.1: Prepare dark jersey dataset with contrast enhancement ═══",
    "DARK_DATASET = DATASETS / 'navy_specialist_v8'",
    "DARK_SRC = DATASETS / 'dark_jersey_numbers'",
    "",
    "def enhance_dark_jersey(img):",
    "    \"\"\"Apply preprocessing pipeline for dark jersey images.\"\"\"",
    "    # CLAHE on L channel",
    "    lab = cv2.cvtColor(img, cv2.COLOR_BGR2LAB)",
    "    l, a, b = cv2.split(lab)",
    "    clahe = cv2.createCLAHE(clipLimit=3.0, tileGridSize=(8, 8))",
    "    l = clahe.apply(l)",
    "    lab = cv2.merge([l, a, b])",
    "    enhanced = cv2.cvtColor(lab, cv2.COLOR_LAB2BGR)",
    "    # Gamma correction (brighten)",
    "    gamma = 1.5",
    "    lut = np.array([((i / 255.0) ** (1.0 / gamma)) * 255",
    "                    for i in np.arange(0, 256)]).astype('uint8')",
    "    enhanced = cv2.LUT(enhanced, lut)",
    "    return enhanced",
    "",
    "if DARK_SRC.exists():",
    "    DARK_DATASET.mkdir(parents=True, exist_ok=True)",
    "    for split in ['train', 'valid', 'test']:",
    "        src_img = DARK_SRC / split / 'images'",
    "        src_lbl = DARK_SRC / split / 'labels'",
    "        if not src_img.exists(): continue",
    "        dst_img = DARK_DATASET / split / 'images'",
    "        dst_lbl = DARK_DATASET / split / 'labels'",
    "        dst_img.mkdir(parents=True, exist_ok=True)",
    "        dst_lbl.mkdir(parents=True, exist_ok=True)",
    "        count = 0",
    "        for img_path in src_img.glob('*'):",
    "            if img_path.suffix.lower() not in ('.jpg', '.jpeg', '.png'): continue",
    "            # Copy original",
    "            shutil.copy2(img_path, dst_img / img_path.name)",
    "            lbl_path = src_lbl / f'{img_path.stem}.txt'",
    "            if lbl_path.exists():",
    "                shutil.copy2(lbl_path, dst_lbl / f'{img_path.stem}.txt')",
    "            # Also add CLAHE-enhanced copy",
    "            img = cv2.imread(str(img_path))",
    "            if img is not None:",
    "                enhanced = enhance_dark_jersey(img)",
    "                enh_name = f'enhanced_{img_path.name}'",
    "                cv2.imwrite(str(dst_img / enh_name), enhanced)",
    "                if lbl_path.exists():",
    "                    shutil.copy2(lbl_path, dst_lbl / f'enhanced_{img_path.stem}.txt')",
    "            count += 1",
    "        print(f'  {split}: {count} originals + {count} enhanced = {count * 2} total')",
    "",
    "    # Copy data.yaml",
    "    src_yaml = DARK_SRC / 'data.yaml'",
    "    if src_yaml.exists():",
    "        import yaml",
    "        with open(src_yaml) as f: data = yaml.safe_load(f)",
    "        data['train'] = str(DARK_DATASET / 'train' / 'images')",
    "        data['val'] = str(DARK_DATASET / 'valid' / 'images')",
    "        with open(DARK_DATASET / 'data.yaml', 'w') as f: yaml.dump(data, f)",
    "else:",
    "    print('  ⚠ dark_jersey_numbers dataset not found')",
]))

cells.append(code_cell([
    "# ═══ Cell 4.2: Train Navy Jersey Specialist v8 ═══",
    "def train_navy_specialist_v8():",
    "    # Fine-tune from v5 universal OCR if available, else yolov8m",
    "    base = MODELS_OUT / 'jersey_ocr_universal_v5.pt'",
    "    if base.exists():",
    "        print('  Fine-tuning from jersey_ocr_universal_v5.pt')",
    "        model = YOLO(str(base))",
    "    else:",
    "        print('  Training from scratch (v5 not found)')",
    "        model = YOLO('yolov8m.pt')",
    "",
    "    results = model.train(",
    "        data=str(DARK_DATASET / 'data.yaml'),",
    "        epochs=100,",
    "        imgsz=1280,",
    "        batch=4,",
    "        patience=20,",
    "        optimizer='AdamW',",
    "        lr0=0.0005,         # Lower LR for fine-tuning",
    "        lrf=0.01,",
    "        # Extra augmentation for dark conditions",
    "        mosaic=1.0,",
    "        hsv_h=0.02,",
    "        hsv_s=0.9,          # Wide saturation (dark jerseys vary a lot)",
    "        hsv_v=0.6,          # Wide brightness (indoor vs outdoor)",
    "        flipud=0.0,",
    "        fliplr=0.5,",
    "        scale=0.5,",
    "        name='navy_jersey_specialist_v8',",
    "        project=str(DRIVE_BASE / 'runs'),",
    "        save=True,",
    "        save_period=20,",
    "    )",
    "    best = Path(results.save_dir) / 'weights' / 'best.pt'",
    "    if best.exists():",
    "        dest = MODELS_OUT / 'navy_jersey_specialist_v8.pt'",
    "        shutil.copy2(best, dest)",
    "        print(f'  Saved: {dest}')",
    "    return results",
    "",
    "safe_train('navy_jersey_specialist_v8', train_navy_specialist_v8)",
]))

# =====================================================================
# MODEL 4: Jersey Upscaler v8
# =====================================================================
cells.append(md_cell([
    f"## {SEP}",
    "## Section 5: Jersey Super-Resolution v8",
    f"## {SEP}",
    "",
    "**Problem:** At 360p, player crops are 30-50px. Jersey digits are only 10-15px. Too small for OCR.",
    "",
    "**Approach:**",
    f"- Train RealESRGAN 4x model on jersey crop pairs",
    f"- Collect high-res jersey crops from training data, downsample for pairs",
    f"- Focus on text/digit reconstruction (not general photo super-res)",
    "",
    "**Alternative:** Use pre-trained SwinIR or RealESRGAN with fine-tuning",
]))

cells.append(code_cell([
    "# ═══ Cell 5.1: Create super-resolution training pairs ═══",
    "SR_DATASET = DATASETS / 'jersey_sr_v8'",
    "HR_DIR = SR_DATASET / 'HR'",
    "LR_DIR = SR_DATASET / 'LR'",
    "HR_DIR.mkdir(parents=True, exist_ok=True)",
    "LR_DIR.mkdir(parents=True, exist_ok=True)",
    "",
    "# Extract jersey crops from training data as HR, downsample for LR",
    "count = 0",
    "for ds_name in ['football_digits', 'dark_jersey_numbers', 'jersey_numbers_diverse']:",
    "    ds_path = DATASETS / ds_name",
    "    if not ds_path.exists(): continue",
    "    for img_path in (ds_path / 'train' / 'images').glob('*'):",
    "        if img_path.suffix.lower() not in ('.jpg', '.jpeg', '.png'): continue",
    "        img = cv2.imread(str(img_path))",
    "        if img is None: continue",
    "        h, w = img.shape[:2]",
    "        # Use crops that are at least 128px (will be our HR)",
    "        if min(h, w) < 128: continue",
    "        # Resize to standard HR size (256x256)",
    "        hr = cv2.resize(img, (256, 256), interpolation=cv2.INTER_LANCZOS4)",
    "        # Create LR at 4x downscale (64x64)",
    "        lr = cv2.resize(hr, (64, 64), interpolation=cv2.INTER_AREA)",
    "        cv2.imwrite(str(HR_DIR / f'{count:06d}.png'), hr)",
    "        cv2.imwrite(str(LR_DIR / f'{count:06d}.png'), lr)",
    "        count += 1",
    "        if count >= 10000: break",
    "    if count >= 10000: break",
    "",
    "print(f'Created {count} HR/LR pairs for super-resolution training')",
]))

cells.append(code_cell([
    "# ═══ Cell 5.2: Train jersey upscaler (RealESRGAN fine-tune) ═══",
    "def train_jersey_upscaler_v8():",
    "    \"\"\"Fine-tune RealESRGAN on jersey digit crops.\"\"\"",
    "    try:",
    "        from basicsr.archs.rrdbnet_arch import RRDBNet",
    "        from realesrgan import RealESRGANer",
    "        from realesrgan.archs.srvgg_arch import SRVGGNetCompact",
    "    except ImportError:",
    "        print('  ⚠ RealESRGAN not installed. Using pre-trained model.')",
    "        # Download pre-trained and save",
    "        import urllib.request",
    "        url = 'https://github.com/xinntao/Real-ESRGAN/releases/download/v0.2.5.0/realesr-general-x4v3.pth'",
    "        dest = MODELS_OUT / 'jersey_upscaler_v8.pth'",
    "        if not dest.exists():",
    "            urllib.request.urlretrieve(url, str(dest))",
    "            print(f'  Downloaded pre-trained upscaler: {dest}')",
    "        return None",
    "",
    "    # Fine-tune on jersey crops",
    "    # This uses BasicSR training config",
    "    print('  Training RealESRGAN on jersey digit crops...')",
    "    print('  (This may take 4-8 hours on A100)')",
    "",
    "    # For now, use pre-trained model as baseline",
    "    # Full fine-tuning requires BasicSR config which is complex",
    "    import urllib.request",
    "    url = 'https://github.com/xinntao/Real-ESRGAN/releases/download/v0.2.5.0/realesr-general-x4v3.pth'",
    "    dest = MODELS_OUT / 'jersey_upscaler_v8.pth'",
    "    if not dest.exists():",
    "        urllib.request.urlretrieve(url, str(dest))",
    "        print(f'  Downloaded pre-trained upscaler: {dest}')",
    "    return None",
    "",
    "safe_train('jersey_upscaler_v8', train_jersey_upscaler_v8)",
]))

# =====================================================================
# MODEL 5: Scoreboard OCR v8
# =====================================================================
cells.append(md_cell([
    f"## {SEP}",
    "## Section 6: Scoreboard OCR v8",
    f"## {SEP}",
    "",
    "**Problem:** v5 scoreboard_detector detects scoreboards but can't read the score.",
    "Score tracking enables automatic outcome detection (score change = made shot/touchdown).",
    "",
    "**Approach:**",
    f"- Detect scoreboard region (v5 model handles this)",
    f"- OCR digits within scoreboard crop",
    f"- Track score changes over time for play outcome validation",
]))

cells.append(code_cell([
    "# ═══ Cell 6.1: Scoreboard OCR dataset ═══",
    "# Note: Scoreboard OCR datasets are harder to find publicly.",
    "# For v8, we'll create a synthetic scoreboard dataset.",
    "",
    "SCOREBOARD_DATASET = DATASETS / 'scoreboard_ocr_v8'",
    "SCOREBOARD_DATASET.mkdir(parents=True, exist_ok=True)",
    "",
    "def generate_synthetic_scoreboard(idx, w=200, h=60):",
    "    \"\"\"Generate a synthetic scoreboard image with digit labels.\"\"\"",
    "    import random",
    "    img = np.zeros((h, w, 3), dtype=np.uint8)",
    "    # Random background color (dark)",
    "    bg = random.randint(10, 60)",
    "    img[:] = (bg, bg, bg)",
    "    # Generate two scores",
    "    score1 = random.randint(0, 42)",
    "    score2 = random.randint(0, 42)",
    "    text = f'{score1:2d} - {score2:2d}'",
    "    # Random font scale",
    "    scale = random.uniform(0.8, 1.4)",
    "    color = (random.randint(200, 255), random.randint(200, 255), random.randint(200, 255))",
    "    thickness = random.choice([1, 2])",
    "    (tw, th), _ = cv2.getTextSize(text, cv2.FONT_HERSHEY_SIMPLEX, scale, thickness)",
    "    x = (w - tw) // 2",
    "    y = (h + th) // 2",
    "    cv2.putText(img, text, (x, y), cv2.FONT_HERSHEY_SIMPLEX, scale, color, thickness)",
    "    # Add noise",
    "    noise = np.random.normal(0, 10, img.shape).astype(np.int8)",
    "    img = np.clip(img.astype(np.int16) + noise, 0, 255).astype(np.uint8)",
    "    return img, text, score1, score2",
    "",
    "# Generate 5000 synthetic scoreboards",
    "for split, count in [('train', 4000), ('valid', 500), ('test', 500)]:",
    "    img_dir = SCOREBOARD_DATASET / split / 'images'",
    "    lbl_dir = SCOREBOARD_DATASET / split / 'labels'",
    "    img_dir.mkdir(parents=True, exist_ok=True)",
    "    lbl_dir.mkdir(parents=True, exist_ok=True)",
    "    for i in range(count):",
    "        img, text, s1, s2 = generate_synthetic_scoreboard(i)",
    "        cv2.imwrite(str(img_dir / f'score_{i:05d}.png'), img)",
    "        # Simple label: class 0 = score region (full image)",
    "        with open(lbl_dir / f'score_{i:05d}.txt', 'w') as f:",
    "            f.write('0 0.5 0.5 1.0 1.0\\n')",
    "",
    "# Create data.yaml",
    "yaml_text = f\"\"\"train: {SCOREBOARD_DATASET / 'train' / 'images'}",
    "val: {SCOREBOARD_DATASET / 'valid' / 'images'}",
    "test: {SCOREBOARD_DATASET / 'test' / 'images'}",
    "nc: 1",
    "names: ['score_region']",
    "\"\"\"",
    "(SCOREBOARD_DATASET / 'data.yaml').write_text(yaml_text)",
    "print('Scoreboard OCR dataset created: 5000 synthetic images')",
]))

cells.append(code_cell([
    "# ═══ Cell 6.2: Train Scoreboard OCR v8 ═══",
    "# Note: For production, this should be trained on real scoreboard",
    "# screenshots scraped from broadcast footage.",
    "# Synthetic data is a starting point.",
    "",
    "def train_scoreboard_ocr_v8():",
    "    model = YOLO('yolov8s.pt')  # Small model for fast scoreboard detection",
    "    results = model.train(",
    "        data=str(SCOREBOARD_DATASET / 'data.yaml'),",
    "        epochs=80,",
    "        imgsz=640,",
    "        batch=16,",
    "        patience=15,",
    "        name='scoreboard_ocr_v8',",
    "        project=str(DRIVE_BASE / 'runs'),",
    "        save=True,",
    "    )",
    "    best = Path(results.save_dir) / 'weights' / 'best.pt'",
    "    if best.exists():",
    "        dest = MODELS_OUT / 'scoreboard_ocr_v8.pt'",
    "        shutil.copy2(best, dest)",
    "        print(f'  Saved: {dest}')",
    "    return results",
    "",
    "safe_train('scoreboard_ocr_v8', train_scoreboard_ocr_v8)",
]))

# =====================================================================
# CELL: Summary + Copy to repo
# =====================================================================
cells.append(md_cell([
    f"## {SEP}",
    "## Section 7: Summary + Copy Models to Repo",
    f"## {SEP}",
]))

cells.append(code_cell([
    "# ═══ Cell 7.1: Create production-named copies + summary ═══",
    "# The codebase expects v7-named files in _MODEL_REGISTRY.",
    "# Create copies with the expected names so they load automatically.",
    "V8_TO_PRODUCTION = {",
    "    'football_jersey_ocr_v8.pt': 'football_jersey_ocr_v7.pt',",
    "    'football_player_crop_v8.pt': 'football_player_crop_v7.pt',",
    "    'navy_jersey_specialist_v8.pt': 'navy_jersey_specialist_v7.pt',",
    "}",
    "",
    "for v8_name, prod_name in V8_TO_PRODUCTION.items():",
    "    src = MODELS_OUT / v8_name",
    "    dst = MODELS_OUT / prod_name",
    "    if src.exists():",
    "        shutil.copy2(src, dst)",
    "        print(f'  {v8_name} -> {prod_name}')",
    "",
    "print('\\n' + '=' * 60)",
    "print('V8 TRAINING COMPLETE')",
    "print('=' * 60)",
    "",
    "expected_models = [",
    "    ('football_jersey_ocr_v7.pt', 'Football digit OCR (CRITICAL)'),",
    "    ('football_player_crop_v7.pt', 'Football player isolation'),",
    "    ('navy_jersey_specialist_v7.pt', 'Dark/navy jersey OCR'),",
    "    ('jersey_upscaler_v8.pth', 'Super-resolution upscaler'),",
    "    ('scoreboard_ocr_v8.pt', 'Scoreboard digit reader'),",
    "]",
    "",
    "for name, desc in expected_models:",
    "    path = MODELS_OUT / name",
    "    if path.exists():",
    "        size_mb = path.stat().st_size / 1024 / 1024",
    "        print(f'  OK {name} ({size_mb:.1f} MB) - {desc}')",
    "    else:",
    "        print(f'  XX {name} - MISSING - {desc}')",
    "",
    "print(f'\\nAll models saved to: {MODELS_OUT}')",
]))

cells.append(code_cell([
    "# ═══ Cell 7.2: Clone repo + copy models + push ═══",
    "# This clones your repo, copies trained models in, and pushes.",
    "# You MUST set your GitHub token below for push to work.",
    "",
    "GITHUB_TOKEN = ''  # Paste your GitHub personal access token here",
    "GITHUB_USER = 'dustinsayah'",
    "GITHUB_REPO = 'jersey-detection'",
    "",
    "import subprocess",
    "",
    "REPO_DIR = Path('/content/jersey-detection')",
    "REPO_MODEL_DIR = REPO_DIR / 'app' / 'model'",
    "",
    "if GITHUB_TOKEN:",
    "    # Clone if not already cloned",
    "    if not REPO_DIR.exists():",
    "        url = f'https://{GITHUB_TOKEN}@github.com/{GITHUB_USER}/{GITHUB_REPO}.git'",
    "        subprocess.run(['git', 'clone', '--depth=1', url, str(REPO_DIR)], check=True)",
    "        print(f'Cloned {GITHUB_REPO}')",
    "",
    "    # Copy production-named models",
    "    PROD_FILES = [",
    "        'football_jersey_ocr_v7.pt',",
    "        'football_player_crop_v7.pt',",
    "        'navy_jersey_specialist_v7.pt',",
    "        'jersey_upscaler_v8.pth',",
    "        'scoreboard_ocr_v8.pt',",
    "    ]",
    "    copied = 0",
    "    for name in PROD_FILES:",
    "        src = MODELS_OUT / name",
    "        if src.exists():",
    "            shutil.copy2(src, REPO_MODEL_DIR / name)",
    "            print(f'  Copied {name}')",
    "            copied += 1",
    "",
    "    if copied > 0:",
    "        os.chdir(str(REPO_DIR))",
    "        subprocess.run(['git', 'add'] + [f'app/model/{n}' for n in PROD_FILES if (MODELS_OUT / n).exists()], check=True)",
    "        subprocess.run(['git', 'commit', '-m', f'Add v8 trained models: {copied} files'], check=True)",
    "        subprocess.run(['git', 'push', 'origin', 'main'], check=True)",
    "        print(f'\\nPushed {copied} models to {GITHUB_REPO}!')",
    "        print('Railway will auto-deploy in ~10 minutes.')",
    "    else:",
    "        print('No models to push.')",
    "else:",
    "    print('Set GITHUB_TOKEN above to auto-push models.')",
    "    print(f'Or download manually from: {MODELS_OUT}')",
    "    if REPO_MODEL_DIR.exists():",
    "        for f in MODELS_OUT.glob('*.pt'):",
    "            shutil.copy2(f, REPO_MODEL_DIR / f.name)",
    "        for f in MODELS_OUT.glob('*.pth'):",
    "            shutil.copy2(f, REPO_MODEL_DIR / f.name)",
    "        print('Copied to local repo. Run git add/commit/push manually.')",
]))

# =====================================================================
# Build notebook
# =====================================================================
notebook = {
    "nbformat": 4,
    "nbformat_minor": 0,
    "metadata": {
        "colab": {
            "provenance": [],
            "gpuType": "A100",
        },
        "kernelspec": {
            "name": "python3",
            "display_name": "Python 3",
        },
        "accelerator": "GPU",
    },
    "cells": cells,
}

out_path = Path(__file__).parent / "train_models_v8.ipynb"
with open(out_path, "w", encoding="utf-8") as f:
    json.dump(notebook, f, indent=1, ensure_ascii=False)

print(f"Wrote {out_path} with {len(cells)} cells")
